config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  get '/how-it-works', to: 'static_pages#how-it-works'
  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'


  get '/signup', to: 'hoac_users#new'
  post '/signup', to: 'hoac_users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/sign-in', to: 'doctor_sessions#new'
  post '/sign-in', to: 'doctor_sessions#create'
  delete '/sign-out', to: 'doctor_sessions#destroy'

  get '/doctors/:id', to: 'doctors#dashboard', as: :dashboard
  get '/doctor/:id', to: 'doctors#profile', as: :profile

  get '/sign-up', to: 'doctors#new'
  post '/sign-up', to: 'doctors#create'

  get '/hoac_user_appointments/:id', to: 'appointments#list', as: :users_appointments
  get '/appointment_details/:id', to:'appointments#show', as: :appointment_details





  resources :hoac_users
  resources :doctors

  resources :hoac_users do
    resources :doctors do
      resources :appointments, except: [:index]
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hoac_user.rb
class HoacUser < ApplicationRecord
  attr_accessor :remember_token
  has_many :appointments
  has_many :doctors
  before_save { self.email = email.downcase }
  before_save { self.name = name.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX},
            uniqueness: { case_sensitive: false }
  #validates :mobile_number, :numericality => true

  has_secure_password
  validates :password, presence: true, length: { minimum: 6}, allow_nil: true


  #validates :status, presence: true
#  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  #Returns the hash digest of the given string
  #this method is used to generate cookies for users
  def HoacUser.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  #returns a random token
  #this method generate random base_64 strings
  def HoacUser.new_token
    SecureRandom.urlsafe_base64
  end

  #Remembers a HoacUser in the database for use in persistent sessions
  def remember
    self.remember_token = HoacUser.new_token
    update_attribute(:remember_digest, HoacUser.digest(remember_token))
  end

  #Returns true if the given token  matches the digest
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  #Forgets a user
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/hoac_users_controller.rb
class HoacUsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :show] #this prevent users trying to access restricted
  #pages
  before_action :correct_user, only: [:edit, :update, :show] #prevent current user from editing others infos or see it
  def index
    redirect_to signup_path
  end

   def show
   	 @user = HoacUser.find(params[:id])
     @doctors = Doctor.all
   end
  def new
  	@user = HoacUser.new
  end

  def create
  	@user = HoacUser.new(user_params)
  	if @user.save
      log_in @user
  		flash[:success] = "Welcome to HoAc online appointments"
  		redirect_to @user
  	else
  		render 'new'
  	 end
  end

  def edit
    @user = HoacUser.find(params[:id])

  end

  def update
    @user = HoacUser.find(params[:id])
    if @user.update_attributes(edit_profile)
      flash[:success] = "Profile updated!"
      redirect_to @user
      else
        render 'edit'
    end
  end

  def destroy
    HoacUser.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to current_user
  end


  #method below here are private
  private
  def user_params
  		params.require(:hoac_user).permit(:name, :email,
                                        :password, :password_confirmation)
  end

  def edit_profile
    params.require(:hoac_user).permit(:name, :city, :street,
                                      :first_name, :last_name,
                                      :mobile_number, :dob,
                                      :gender, :password, :password_confirmation)
  end

  #confirm  a logged_in user
  def logged_in_user
    unless logged_in?
      store_url_destination
      flash[:danger] = "please log in."
      redirect_to login_path
    end
  end

  #confirm  the current user
  #take the login user to his and only edit profile
  def correct_user
    @user = HoacUser.find(params[:id])
    redirect_to(edit_hoac_user_path) unless current_user?(@user)
  end

  #confirm a user as an admin
  def admin_user
   redirect_to(root_url) unless correct_user.admin?    
  end


end

app/helpers/hoac_users_helper.rb
module HoacUsersHelper

	# Returns the Gravatar for the given user.
  def gravatar_for(user, size: 150)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
 
    	image_tag(gravatar_url, alt: user.name, class: "gravatar")
  
  end
end

app/views/hoac_users/docInfos.html.erb
<%= provide(:title, "Doctor's Info") %>
<div class="large-6 large-offset-3">
  <% flash.each do |message_type, message| %>
      <div class="<%= message_type %>">

        <p><%= message %></p>

      </div>
  <% end %>
</div>
<h1>Doctor's Details</h1>

app/views/hoac_users/edit.html.erb
<%provide(:title, 'Edit user')%>
<%provide(:button_text, 'Save changes') %>

<div class="row">
<center><h1>Update your profile</h1></center>
   <div class="large-5 columns">
   	 <h1>Content here if you like</h1>
   	 <h1>Content here if you like</h1>
   	 <h1>Content here if you like</h1>
   	 <h1>Content here if you like</h1>
   	 <h1>Content here if you like</h1>
   	 
   </div>
	<div class="large-7 columns"  style="background-color: #f5f5f5; border-radius: 2px">
	
	<%= render 'hoac_users/shared/edit_profile' %>
	</div>
</div>

<%= render 'hoac_users/shared/hoacfooter' %>

app/views/hoac_users/new.html.erb
<% provide(:title, 'Sign up') %>
<%provide(:button_text, 'Create my account') %>

<div class="row">
	<div class="large-6 large-offset-3 columns">
	<div style="text-align: center;"><h1>Sign up</h1></div>
	<%= render 'hoac_users/shared/form' %>
	</div>
</div>

<div class="row flush-bottom2">
	<div class="large-12 columns center-text">
		<h3>OR</h3>
		<p>Have an account ? <span><%= link_to 'log in', login_path%></span></p> 
	</div>
</div>

<%= render 'hoac_users/shared/hoacfooter' %>

app/views/hoac_users/show.html.erb
<%provide(:title, @user.name)  %>


<!-- the left content menu -->
<div class="large-3 columns" style="background-color: #BBBBBB">
	<!-- the section where user profile and other stuffs will be placed-->
		<div class="row" style="margin-bottom: 10px;">
      <h4 style="margin: 10px 0 0 15px;"><%=@user.name.capitalize %></h4>
      <div class="large-12 columns"><hr></div>
				<div class="small-6 columns">
					<%= image_tag('images.jpg', style: "border-radius: 100px") %>
				</div>
					<div class="small-6 columns">
            <p><%= @user.email%></p>
            <p><%= @user.mobile_number%></p>
            <p><%= "#{@user.city}, #{@user.street}"%></p>
					</div>
						

		</div>
  		
  		<hr>
  		<!-- a list that user can switched from -->
  <div class="row  side-bar-items ">
    <div class="large-10 columns" style="margin-bottom: 10px">
  			<ul class="menu vertical large-12">
          <li><a href="#" class="button">Hospitals</a></li>
  				<hr>
  				<li><a href="#" class="button">Find Doctors</a></li>
          <li><%= link_to "Appointments", users_appointments_path , class: 'button'%></li>
			</ul>
    </div>
		 
  </div>

</div>


	<!-- main content div where doctors list will be displayed-->
	<div class="large-9 columns" id="main-content">
		
		<div class="row">
			<div class="large-12 columns">
				<% @doctors.each do |doctor| %>
				<div class="large-12 columns"  id="doctors">
				 <div class="row">
				 	<div class="large-5 columns">
						<%= image_tag('images.jpg') %>
				 	</div>
				 	<div class="large-7 columns">
				 		<h4>Dr <%=doctor.uid%></h4>
            <%= link_to 'Details', profile_path(doctor.id)%>
					<p><%=doctor.department.department_name %></p>
					<p>General Hospital Yaoundé</p>
					<p> Mon - Fri </p>
					 <div style="text-align: center;"><%= link_to 'book appointment', new_hoac_user_doctor_appointment_path(@user.id, doctor.id)%></p></div>
				 	</div>

				 </div>
					
				</div>
				<% end -%>

			</div>


			<!-- The right side bar where news feed and other stuffs can be placed-->
			<!--<div class="large-5 columns">
			<div class="row">
				<div class="large-12 columns"  id="doctors" >
					<h1>right</h1>
					<h4>Other Stuffs</h4>
					<h4>Other Stuffs</h4>
					<h4>Other Stuffs</h4>
					<h4>Other Stuffs</h4>
					<h4>Other Stuffs</h4>
				</div>
				<div class="large-12 columns">
					<p>privacy . terms</p>

				</div>
			</div>
				
			</div>-->
		</div>
	</div>