config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  get '/how-it-works', to: 'static_pages#how-it-works'
  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'


  get '/signup', to: 'hoac_users#new'
  post '/signup', to: 'hoac_users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/sign-in', to: 'doctor_sessions#new'
  post '/sign-in', to: 'doctor_sessions#create'
  delete '/sign-out', to: 'doctor_sessions#destroy'

  get '/doctors/:id', to: 'doctors#dashboard', as: :dashboard
  get '/doctor/:id', to: 'doctors#profile', as: :profile

  get '/sign-up', to: 'doctors#new'
  post '/sign-up', to: 'doctors#create'

  get '/hoac_user_appointments/:id', to: 'appointments#list', as: :users_appointments
  get '/appointment_details/:id', to:'appointments#show', as: :appointment_details





  resources :hoac_users
  resources :doctors

  resources :hoac_users do
    resources :doctors do
      resources :appointments, except: [:index]
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :hoac_user
  belongs_to :doctor
  default_scope -> { order(created_at: :desc) }
  validates :hoac_user_id, presence: true
  validates :doctor_id, presence: true
  validates :name, presence: true
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
before_action :logged_in_user, only: [:create, :new]
before_action :find_patient, only: [:new, :create]

  def list
    @user = HoacUser.find(params[:id])
    @appointments = @user.appointments.all
  end

  def show
   @appointment = Appointment.find(params[:id])
  end

  def new
   @appointment = Appointment.new
   #@patient = HoacUser.find(params[:hoac_user_id] || params[:id])
  # @doctor = Doctor.find(params[:doctor_id] || params[:id])
  end

  def create
    @appointment = Appointment.new(appointments_params)
    if @appointment.save
      flash[:success] = "Appointment made!"
      redirect_to current_user
    else
        render 'new'
    end
  end

  private
  def appointments_params
    params.require(:appointment).permit(:name, :appointment_date, :hoac_user_id, :doctor_id)
  end

def find_patient
  @patient = HoacUser.find(params[:hoac_user_id] || params[:id])
  @doctor = Doctor.find(params[:doctor_id] || params[:id])
end






  #confirm  the current user
  #take the login user to his and only edit profile
  #def correct_user
    #@user = HoacUser.find(params[:id])
    #redirect_to(edit_hoac_user_path) unless current_user?(@patient)
  #end

  #confirm  a logged_in user
  def logged_in_user
    unless logged_in?
      store_url_destination
      flash[:danger] = "please log in."
      redirect_to login_path
    end
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/list.html.erb
<%provide(:title, "All Appointments") %>
<h4>I am index page</h4>
<%if @appointments.empty? %>
    <h4>List Is Empty</h4>
    <%else%>
    <h4>Displaying Appointments</h4>
    <% @appointments.each do |appointment| %>
        <h4>Dr. <%= appointment.doctor.uid %> <%= ", appointment => " %><%= appointment.name %>
        <%= link_to "View", appointment_details_path(appointment.id), style: 'color: blue'%>
        </h4>

        <%end%>
<% end%>

app/views/appointments/new.html.erb
<%provide(:title, "Appointment") %>
<%provide(:button_text, 'Shedule Appointment') %>
<div class="row">
  <div class="large-6 large-offset-3 columns">
    <div style="text-align: center;"><h1>Sheduling Appointment with Dr <%=@doctor.uid.to_s%></h1></div>
    <%= render 'appointments/shared/form' %>
  </div>
</div>

app/views/appointments/show.html.erb
<% provide(:title, "Details Of Appointment") %>
<h1><%= @appointment.name%></h1>