config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  get '/how-it-works', to: 'static_pages#how-it-works'
  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'


  get '/signup', to: 'hoac_users#new'
  post '/signup', to: 'hoac_users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/sign-in', to: 'doctor_sessions#new'
  post '/sign-in', to: 'doctor_sessions#create'
  delete '/sign-out', to: 'doctor_sessions#destroy'

  get '/doctors/:id', to: 'doctors#dashboard', as: :dashboard
  get '/doctor/:id', to: 'doctors#profile', as: :profile

  get '/sign-up', to: 'doctors#new'
  post '/sign-up', to: 'doctors#create'

  get '/hoac_user_appointments/:id', to: 'appointments#list', as: :users_appointments
  get '/appointment_details/:id', to:'appointments#show', as: :appointment_details





  resources :hoac_users
  resources :doctors

  resources :hoac_users do
    resources :doctors do
      resources :appointments, except: [:index]
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hoac_user.rb
class HoacUser < ApplicationRecord
  attr_accessor :remember_token
  has_many :appointments
  has_many :doctors
  before_save { self.email = email.downcase }
  before_save { self.name = name.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX},
            uniqueness: { case_sensitive: false }
  #validates :mobile_number, :numericality => true

  has_secure_password
  validates :password, presence: true, length: { minimum: 6}, allow_nil: true


  #validates :status, presence: true
#  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  #Returns the hash digest of the given string
  #this method is used to generate cookies for users
  def HoacUser.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  #returns a random token
  #this method generate random base_64 strings
  def HoacUser.new_token
    SecureRandom.urlsafe_base64
  end

  #Remembers a HoacUser in the database for use in persistent sessions
  def remember
    self.remember_token = HoacUser.new_token
    update_attribute(:remember_digest, HoacUser.digest(remember_token))
  end

  #Returns true if the given token  matches the digest
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  #Forgets a user
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/hoac_users_controller.rb
class HoacUsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :show] #this prevent users trying to access restricted
  #pages
  before_action :correct_user, only: [:edit, :update, :show] #prevent current user from editing others infos or see it
  def index
    redirect_to signup_path
  end

   def show
   	 @user = HoacUser.find(params[:id])
     @doctors = Doctor.all
   end
  def new
  	@user = HoacUser.new
  end

  def create
  	@user = HoacUser.new(user_params)
  	if @user.save
      log_in @user
  		flash[:success] = "Welcome to HoAc online appointments"
  		redirect_to @user
  	else
  		render 'new'
  	 end
  end

  def edit
    @user = HoacUser.find(params[:id])

  end

  def update
    @user = HoacUser.find(params[:id])
    if @user.update_attributes(edit_profile)
      flash[:success] = "Profile updated!"
      redirect_to @user
      else
        render 'edit'
    end
  end

  def destroy
    HoacUser.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to current_user
  end


  #method below here are private
  private
  def user_params
  		params.require(:hoac_user).permit(:name, :email,
                                        :password, :password_confirmation)
  end

  def edit_profile
    params.require(:hoac_user).permit(:name, :city, :street,
                                      :first_name, :last_name,
                                      :mobile_number, :dob,
                                      :gender, :password, :password_confirmation)
  end

  #confirm  a logged_in user
  def logged_in_user
    unless logged_in?
      store_url_destination
      flash[:danger] = "please log in."
      redirect_to login_path
    end
  end

  #confirm  the current user
  #take the login user to his and only edit profile
  def correct_user
    @user = HoacUser.find(params[:id])
    redirect_to(edit_hoac_user_path) unless current_user?(@user)
  end

  #confirm a user as an admin
  def admin_user
   redirect_to(root_url) unless correct_user.admin?    
  end


end

app/helpers/hoac_users_helper.rb
module HoacUsersHelper

	# Returns the Gravatar for the given user.
  def gravatar_for(user, size: 150)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
 
    	image_tag(gravatar_url, alt: user.name, class: "gravatar")
  
  end
end

app/views/hoac_users/shared/_edit_profile.html.erb
<%= form_for @user do |f| %>
	<%= render 'hoac_users/shared/error_messages', object: @user %>
      <%= f.label "Profile Name" %>
      <%= f.text_field :name %>
      <div class="row">
            <div class="large-6 columns">
                  <%= f.label "First Name" %>
                  <%= f.text_field :first_name %>
            </div>
            <div class="large-6 columns">
                    <%= f.label "Last Name" %>
                    <%= f.text_field :last_name %>
            </div>
      </div>
      

      <h4>Personal Infos</h4>
      <%= f.label "Date Of Birth" %>
      <%= f.text_field :dob, id: 'dob' %>

      
      <%= f.label "Gender" %>
      <div class="row">
            <div class="large-2 columns">
            <div class="row">
                  <div class="large-2 columns">
                         <%= f.label "Male" %>
                        <%= f.radio_button(:gender, 'M')%>

                  </div>
                  <div class="large-2 columns">
                        <%= f.label "Female" %>
                        <%= f.radio_button(:gender, 'F')%>

                  </div>
            </div>
                 
            </div>
      </div>

      <h4>Contact Info</h4>
      <%= f.label :city %>
      <%= f.text_field :city, placeholder: "enter your city here" %>

      <%= f.label :street %>
      <%= f.text_field :street, placeholder: 'enter your street here'%>

      <%= f.label "Mobile Number" %>
      <%= f.text_field :mobile_number %>
      
     <!-- <%= f.label :email %>
      <%= f.email_field :email %>-->

    <h4>Security</h4>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>



      <center><%= f.submit yield(:button_text), class: "button", style: "border-radius: 2px" %></center>
<% end %>

app/views/hoac_users/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div class="error_explanation">
	<div data-alert class="has-errors">
  		The form contains <%= pluralize(object.errors.count, "error") %>.
	</div>
	<ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
</div>
<%end %>

app/views/hoac_users/shared/_form.html.erb
<%= form_for @user do |f| %>
	<%= render 'hoac_users/shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>


      <%= f.submit yield(:button_text), class: "button large-12" %>
<% end %>

app/views/hoac_users/shared/_hoacfooter.html.erb
<div class="large-12 columns" style="margin-top: 10px; background: #004d40">
	<div class="row">
		<div class="large-5 columns" style="color: white; margin-top: 30px;">
			<h6 style="font-size: 12px">HoAC Online is the trade name of Health Management System(HMS)</h6>
			<p style="font-size: 10px; margin-top: 25px">© 2016 Health Management System. All rights reserved.</p>
		</div>
		<div class="large-3 columns" style="color: white; margin-top: 10px; text-align: center;">
			<h4>follow us</h4>
		</div>
		<div class="large-4 columns" style="color: white; text-align: center; margin-top: 70px">
				<!--<p>Terms | Privacy | Contacts | Providers</p>-->
				<div class="menu simple">
					<%= link_to "Terms | ", terms_path%>
					<%= link_to "Privacy", privacy_path %>
				</div>

		</div>
	</div>
</div> 

app/views/hoac_users/shared/_hoacheader.html.erb
<nav>
  <div id="sign-login-header">
 
    <div class="top-bar-right">
    <ul class="dropdown vertical medium-horizontal menu"
        data-options="disableHover:true;clickOpen:true" data-dropdown-menu>
      <!--<li><a href="#" class="sign" id="fr">EN</a></li>-->

      
      <% if logged_in?%>
       
       <li><%= link_to 'profile', current_user %></li>
      

       <li>
          <%= link_to 'Account' %>
            <ul class="menu">
             <li><%= link_to 'Logout', logout_path, method: "delete"%></li>

              <li><%= link_to 'Settings', edit_hoac_user_path(current_user)%></li>
      <!-- ... -->
            </ul>
        </li>

        <%elsif logged_in_doctor? %>


          <li><%= link_to "Profile", profile_path(current_doctor)%></li>


          <li>
            <%= link_to 'Account', style: "background-color: #ffffff" %>
            <ul class="menu">
              <li><%= link_to 'Logout', sign_out_path, method: "delete"%></li>

              <li><%= link_to 'Settings', edit_doctor_path(current_doctor)%></li>
              <li><%= link_to 'More', edit_doctor_path(current_doctor)%></li>
              <!-- ... -->
            </ul>
          </li>
        <% else %>


      <li><%= link_to "sign up", signup_path%></li>
      <li><%= link_to 'log in', login_path%></li>
    <%end%>

    </ul>
  </div>
  </div>

  <div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li><%= link_to '', "#", class: 'logo' %></li>
    </ul>
  </div>
  <div class="menu-centered">
    <ul class="menu center-menu">
      <li><%= link_to "HOME", root_path %></li>

      <% if logged_in? %>
      <li><%= link_to "NOTIFICATIONS", "#"%></li>
       <li><%= link_to "DOCTORS",  "#"%></li>

          <% elsif logged_in_doctor?%>

          <li><%= link_to "DASHBOARD", dashboard_path(current_doctor)%></li>
          <li><%= link_to "NOTIFICATIONS",  "#"%></li>

          <%else%>
          <li><%= link_to "PATIENT?", about_path%></li>
          <li><%= link_to "DOCTORS",  sign_in_path%></li>
          <%end%>
        
    </ul>
  </div>
</div>
</nav>